CREATE TABLE SHEDULE(
     ID INTEGER,
     NAME TEXT NOT NULL,
     TEACHER_ID INTEGER,
     DISCIPLINE_ID INTEGER,
     TIME TIMESTAMP,
     CLASSROOM INTEGER
);

CREATE TABLE DISCIPLINES(
     ID INTEGER,
     NAME TEXT NOT NULL
);

CREATE TABLE GROUP(
    ID INTEGER,
    DEPARTMENT_ID INTEGER,
    NAME TEXT NOT NULL,
    COURSE INTEGER
);

CREATE TABLE STUDENTS(
     ID INTEGER,
     GROUP_ID INTEGER,
     NAME TEXT NOT NULL,
     EMAIL TEXT,
     PHONE TEXT
);

CREATE TABLE TEACHERS(
     ID INTEGER,
     GROUP_ID INTEGER,
     NAME TEXT NOT NULL,
     EMAIL TEXT,
     PHONE TEXT
);

CREATE TABLE FACULTY
(
    ID INTEGER,
    NAME TEXT NOT NULL,
    SHORT_NAME TEXT
);

CREATE TABLE DEPARTMENT
(
    ID INTEGER,
    FACULTY_ID INTEGER,
    NAME TEXT NOT NULL,
    SHORT_NAME TEXT
)